### ISSUE TITLE
dmstodd gives wrong results when degrees has 3 digits

### ISSUE THREAD

**Issue by davidallsopp** [hobu/mgrs#12]
When the degrees of longitude reach 3 digits, the `dmstodd()` method gives incorrect results because the digits representing the minutes are extracted using a 2-character offset relative to the start of the string.

```
>>> import mgrs
>>> m = mgrs.MGRS()
>>> m.dmstodd("110000N")
11.0
>>> m.dmstodd("110000E")
11.0
>>> m.dmstodd("1110000E")
112.66666666666667
>>> m.dmstodd("1110000.00E")
112.66666666666667
```
This can be fixed by changing `[2:-2]` to `[-4:-2]` in two places in `dmstodd()` so that the two digits representing the minutes are extracted relative to the end of the string, not the beginning

**Comment by hobu** [comment]
Thanks for the patch in #13. I will issue a new release to PyPi

**Comment by hobu** [comment]
done https://pypi.python.org/pypi/mgrs
