### ISSUE TITLE
What is the license for libmgsr?

### ISSUE THREAD

**Issue by luipir** [hobu/mgrs#14]
Hi Howard

Would be possible to have an explicit license for this library?

regards, Luigi Pirelli

**Comment by hobu** [comment]
It is MIT, but you are correct there is no license in the repo. 

https://github.com/hobu/mgrs/blob/master/setup.py#L56

**Comment by luipir** [comment]
How sorry I didn't realised

thank you

**Comment by luipir** [comment]
feel free to close the issue if you think that this way to explicit the license is enough

regards

**Comment by hobu** [comment]
> feel free to close the issue if you think that this way to explicit the license is enough

It probably isn't enough for the lawyers.
