### ISSUE TITLE
Wrong tile for a specific point

### ISSUE THREAD

**Issue by tonyVeco** [hobu/mgrs#22]
I have used the mgrs library to get the tile for this point :

Lat = 39.9770
Lon = 116.3810

I get this tile:

50SMK4714425387

this does not correspond to any exsisting Sentinel2 tile. It should be 50TMK

**Comment by apiszcz** [comment]
I tested elsewhere

+39.97700000 +116.38100000 - >  50SMK4714425388

ArcMap 10.7
50SMK4714425388  MGRS

**Comment by tonyVeco** [comment]
yes, this is correct for the MGRS tiling system,  is there any way to use the mgrs package for the Sentinel2 tiling system?

**Comment by hobu** [comment]
So this library returns the correct MGRS location, but you want a different tile out of Sentinel2? I don't see how this is a bug.
