### ISSUE TITLE
get_platform() missing 1 required positional argument: 'archive_root'

### ISSUE THREAD

**Issue by jalldredge2020** [hobu/mgrs#23]
I am receiving an issue since wheel updated. I'm getting an error at 

.env\lib\site-packages\mgrs\core.py in get_windows_platform_name
line 18			   '-' + wheel.pep425tags.get_platform() 

It looks like wheel now expects archive_root to be provided to wheel.pep425tags.get_platform().

**Comment by hobu** [comment]
If you can provide a patch, I will be happy to merge and reissue a release.

**Comment by joshua-hester** [comment]
@hobu I created a pull request
https://github.com/hobu/mgrs/pull/24

Thanks

**Comment by hobu** [comment]
1.3.6 released
