### ISSUE TITLE
Windows Package libmgrs.cp38-win_amd64.pyd Not Found

### ISSUE THREAD

**Issue by robml** [hobu/mgrs#25]
I recently ran this on my Windows machine. When I ran it on a virtual environment in Anaconda, I had no problem, just had to revert the admin-root edit that was raised in a previous issue to get it working. However outside of the virtualenv, using Visual Studio I encounter this error every time I try to import mgrs:

FileNotFoundError: Could not find module 'libmgrs.cp38-win_amd64.pyd'. Try using the full path with constructor syntax.

Any idea what this could be linked to? I haven't had any success so far.

**Comment by dbabbitt** [comment]
Same. Which is weird because it's right in C:\Users\me\.conda\envs\my_environment\Lib\site-packages where it's supposed to be.

**Comment by uetacog** [comment]
Same issue here.

**Comment by hobu** [comment]
Please try 1.3.7 which was just released and includes wheels for all major platforms. Reopen if you still have an issue.

**Comment by qbanguije** [comment]
Hello, I'm having this issue with version 1.4, the error is mgrs.core.MGRSError: Unable to load libmgrs.cp37-win_amd64.pyd. I am using pyinstaller to compile and use mgrs as a hidden import but nothing seems to work.

**Comment by VittoGuest** [comment]
You can find 'libmgrs.cp37-win_amd64.pyd ' in 'C:\Users\....\AppData\Local\Programs\Python\Python39\Lib\site-packages' . Copy and paste it into the mgrs folder ('C:\Users\....\AppData\Local\Programs\Python\Python39\Lib\site-packages\mgrs') . At the end move the entire directory into your project folder
