### ISSUE TITLE
MGRSToUTM only gets zone

### ISSUE THREAD

**Issue by maxmealy** [hobu/mgrs#29]
Thank you for creating and maintaining this library. It's been very useful and easy to use.

The MGRSToUTM method is not working correctly for me. I've had success using the rest of the library, but converting from MGRS to UTM only seems to find the zone.

I am using mgrs 1.3.7 on an Anaconda distribution of Python 3.7. Thanks!

```python
from mgrs import MGRS

convert = MGRS()
coords = "15SWC8081751205".encode('utf-8')

convert.toLatLon(coords)
>>> (38.40542615377341, -92.07439526029498)

convert.MGRSToUTM(coords)
>>>  (15,)

convert.UTMToMGRS(15,'N'.encode('utf-8'),580817,4251205)
>>> b'15SWC8081751205'
```

**Comment by hobu** [comment]
1.3.8 has been released which should fix this issue.

https://pypi.org/project/mgrs/
