### ISSUE TITLE
Unable to load libmgrs.pyd error

### ISSUE THREAD

**Issue by pesikj** [hobu/mgrs#30]
Hello,

I have installed the library by pip (Windows 10, Python 3.8.2) and when I try to import `mgrs`, I see the following error:

```
>>> import mgrs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\repos\hilla-deep-matching\env\lib\site-packages\mgrs\__init__.py", line 1, in <module>
    from . import core
  File "C:\repos\hilla-deep-matching\env\lib\site-packages\mgrs\core.py", line 74, in <module>
    raise MGRSError("Unable to load %s" % lib_name)
mgrs.core.MGRSError: Unable to load libmgrs.pyd
```

Could you please advise which library/dependency I might be missing?

**Comment by hobu** [comment]
For some reason the wheel is not being used. It should be trying to load `libmgrs.cp38-win_amd64.pyd` and that file should exist in your install package.

**Comment by pesikj** [comment]
I do not see such a file. Sorry for asking but is it sufficient to run `pip install mgrs` or is it required to install something else?

**Comment by hobu** [comment]
`pip install mgrs` should have installed the wheel I believe. I don't have time to test this unfortunately. 

if you have MSVC installed, you can clone the repo and issue `python setup.py install` and it should build everything for you.

**Comment by pesikj** [comment]
Sorry, my mistake, I found the file. I solved the issue by creating a copy of `libmgrs.cp38-win_amd64.pyd` named `libmgrs.pyd`.
