### ISSUE TITLE
Using with pyinstaller

### ISSUE THREAD

**Issue by uetacog** [hobu/mgrs#32]
I wanted to leave a note in case anyone gets caught where I was, or I forget what I did.  
  
When using pyinstaller to package something including mgrs, you need to explicitly include the .so file as pyinstaller will not include it.  

`pyinstaller <your options> --add-data=libmgrs.cpython-36m-x86_64-linux-gnu.so:. <name of script>`
1) Notice it is  `.so`  `:`  `.` You are telling it to put the so at the top level
2) The .so is in your site-packages location on ubuntu usually around `~/.local/lib/<python version>/site-packages/`

**Comment by hobu** [comment]
> When using pyinstaller to package something including mgrs, you need to explicitly include the .so file as pyinstaller will not include it.

Is MGRS different than any other wheels in this regard?

**Comment by uetacog** [comment]
I am not a pyinstaller expert by any means. Usually it picks up the imports pretty well or you can pass it the `--paths` or `--hidden-import` options, neither of which solved this issue. I don't think this is out of spec because I found the answer from people using kivy and having similar issues with .kv files.
