### ISSUE TITLE
Fatal error LNK1104 cannot open file 'kernel32.lib'

### ISSUE THREAD

**Issue by Simpson99091** [hobu/mgrs#35]
I get the subject error when trying to pip the package into my virtual environment.  I'm on Windows 20H2.  My python version is 3.9.5.  pip is 21.1.1.

**Comment by Simpson99091** [comment]
LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit code 1104

**Comment by hobu** [comment]
There are wheels available for windows. You are using an old version of Visual Studio, and this is not likely to work, or you are missing SDKs. Look at the github action to see how these wheels are built. 

https://github.com/hobu/mgrs/blob/master/.github/workflows/build.yml
