### ISSUE TITLE
Are N and S backwards?

### ISSUE THREAD

**Issue by bryanaamot** [hobu/mgrs#37]
According to https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system, S is used to designate the Northern Hemisphere. Why does Convert_Geodetic_To_UTM return N for positive latitudes. Shouldn't it be "S"?

**Comment by hobu** [comment]
The codes are coming directly from NGA's converter, so whatever conventions they used is what's reflected in this codebase. This is a 10+ year old repository with no complaints on this particular topic, and I would think it would be a showstopper if it was wrong.
